---
  - include_vars: vault.yml

  - name: checking whether tomcat deployment is already there or not
    shell: docker ps
    register: deploy_existence

  - include: initial.yml
    when: deploy_existence.stdout.find('latest1') == -1

  - include: update.yml
    when: deploy_existence.stdout.find('latest1') != -1
