---
  - include_vars: vault.yml

  - name: checking whether tomcat deployment is already there or not
    shell: docker ps
    register: deploy_existence

  - include: initial.yml
    when: ({% if not deploy_existence | search(\"latest1\") %} True {% else %} False {% endif %})

  - include: update.yml
    when: ({% if deploy_existence | search(\"latest1\") %} True {% else %} False {% endif %})
