---
  - include_vars: vault.yml

  - name: checking whether tomcat deployment is already there or not
    shell: docker ps
    register: deploy_existence

  - include: initial.yml
    when: not deploy_existence | search("latest1")

  - include: update.yml
    when: not deploy_existence | search("latest1")
