---
- name: stop old container
  shell: docker rm $(docker ps -a|grep latest1|awk {'print $1'})
  
- name: remove old images
  shell: docker rmi -f $(docker images|grep latest1|awk {'print $3'})
  
- name: pull new image
  shell: docker pull hackathon:latest1

- name: run latest1
  shell: docker run -dit -p 8077:8080 hackathon:latest1